### ISSUE TITLE
Where can I get the data?

### ISSUE THREAD

**Issue by ocean1100** [charleschiu2012/EVA-Space-Center-Data-Generate#1]
Hello, I'm interested in this project, and I just want to know more about it. So where can I get the data Moon_8K.obj, Moon_8K.mtl, Diffuse_8K.png, thank you!

**Comment by charliie-dev** [comment]
Hi, I bought those items on [this website](https://www.turbosquid.com/FullPreview/Index.cfm/ID/1273668). Hope it helps!

**Comment by charliie-dev** [comment]
BTW, I modified some parameters after some experiments, please check the latest commit.
